apiVersion: v1
kind: Service
metadata:
  labels:
    app: fortune-app
    name: fortune-teller
  name: lb-fortune-teller
  namespace: fortune-teller-ns
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: fortune-app
    name: fortune-teller-pod
  type: LoadBalancer
