apiVersion: v1
kind: Service
metadata:
  namespace: fortune-teller-ns
  name: node-port-fortune-teller
  labels:
    name: fortune-teller
    app: fortune-app
spec:
  type: NodePort
  selector:
    app: fortune-app
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30027