apiVersion: v1
kind: Namespace
metadata:
  name: fortune-teller-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fortune-teller-ns
  name: fortune-teller
  labels:
    name: fortune-teller
    app: fortune-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: fortune-teller-pod
      app: fortune-app
  template:
    metadata:
      name: fortune-teller-pod
      labels:
        name: fortune-teller-pod
        app: fortune-app
    spec:
      containers:
      - name: fortune-app
        image: 140370616192.dkr.ecr.us-east-1.amazonaws.com/fortune-teller:eks-v1
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: fortune-teller-ns
  name: node-port-fortune-teller
  labels:
    name: fortune-teller
    app: fortune-app
spec:
  type: NodePort
  selector:
    app: fortune-app
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30027
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fortune-app
    name: fortune-teller
  name: lb-fortune-teller
  namespace: fortune-teller-ns
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: fortune-app
    name: fortune-teller-pod
  type: LoadBalancer
